language: bash
sudo: required
services:
- docker

before_install:
  - make build-no-cache

install:
  - make init

before_script:
  - make fixtures

script:
  - make run

after_script:
  - make clean
